[package]
name = "error_report"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.7.4"
zip = "0.6.6"
chrono = "0.4.26"
yansi = "0.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

