[package]
name = "vargo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
filetime = "0.2.26"
regex = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.9"
walkdir = "2.5"
yansi = "1.0"
