[package]
name = "rust_verify"
version = "0.1.0"
authors = ["Chris Hawblitzel <Chris.Hawblitzel@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z3 = "0.10.0"
air = { path = "../air" }
vir = { path = "../vir" }
getopts = { git = "https://github.com/utaal/getopts.git", branch = "parse-partial" }

[dev-dependencies]
indoc = "1.0"
