[package]
name = "rust_verify"
version = "0.1.0"
authors = ["Chris Hawblitzel <Chris.Hawblitzel@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
air = { path = "../air" }
vir = { path = "../vir" }
sise = "0.6.0"
getopts = { git = "https://github.com/utaal/getopts.git", branch = "parse-partial" }

[target.'cfg(windows)'.dependencies]
win32job = "1"

[dev-dependencies]
rust_verify_test_macros = { path = "../rust_verify_test_macros" }
regex = "1"

[features]
singular = ["vir/singular", "air/singular"]