title: "Verus â€” Publications and Projects"
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
collections:
  - projects
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
exclude: [Makefile]
pubtypes: ["internal", "external"]
