verus_git_url = "https://github.com/verus-lang/verus.git"
verus_revspec = "jonh/sets-typed-finite"
verus_features = ["singular"]
verus_verify_vstd = true

[[project]]
name = "memory-allocator"
git_url = "https://github.com/verus-lang/verified-memory-allocator.git"
revspec = "main"
crate_root = "verus-mimalloc/lib.rs"
extra_args = [
    "--extern", "libc=build/liblibc.rlib",
    "--rlimit", "240",
]
prepare_script = """
pushd test_libc
cargo clean
cargo +1.82.0 build --release
popd
LIBC_RLIB_NAME=$(find ./test_libc/target/release/deps/ -name 'liblibc-*.rlib')
mkdir -p build
cp $LIBC_RLIB_NAME build/liblibc.rlib
"""

[[project]]
name = "page-table"
git_url = "https://github.com/utaal/verified-nrkernel.git"
revspec = "main"
crate_root = "page-table/src/lib.rs"
extra_args = ["--crate-type=lib", "--rlimit", "60", "--cfg", "feature=\"impl\""]

[[project]]
name = "verified-storage"
git_url = "https://github.com/microsoft/verified-storage.git"
revspec = "veritas"
crate_root = "storage_node/src/lib.rs"
extra_args = [
    "-L", "dependency=deps_hack/target/debug/deps",
    "--extern=deps_hack=deps_hack/target/debug/libdeps_hack.rlib",
]
prepare_script = """
DEBIAN_FRONTEND=noninteractive apt-get update; apt-get install -y libpmem1 libpmemlog1 libpmem-dev libpmemlog-dev llvm-dev clang libclang-dev # verified-storage

cd pmsafe
cargo clean
cargo build 
cd ..

cd deps_hack
cargo clean
cargo build
"""

[[project]]
name = "node-replication"
git_url = "https://github.com/verus-lang/verified-node-replication.git"
revspec = "main"
crate_root = "verified-node-replication/src/lib.rs"
extra_args = ["--crate-type=dylib"]

[[project]]
name = "vest"
git_url = "https://github.com/secure-foundations/vest.git"
revspec = "main"
crate_root = "vest/src/lib.rs"

[[project]]
name = "vest-tls"
git_url = "https://github.com/secure-foundations/vest.git"
revspec = "main"
crate_root = "vest-dsl/tls/src/lib.rs"
extra_args = [
    "--import", "vest=../../vest/vest.verusdata",
    "--extern", "vest=../../vest/libvest.rlib",
    "--rlimit", "50",
]
prepare_script = """
pushd ../../vest
make
popd
"""
