name: crate-updates

on:
#  schedule:
#    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  copy-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

     - name: Update crate versions, if needed
        run: |
          cargo run --manifest-path source/tools/bump_crate_versions/Cargo.toml update
          git config --global user.name 'Version Bumper Bot'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git diff-index --quiet HEAD || git commit -am "Update crate version numbers"

      - name: Publish updated crates to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo run --manifest-path source/tools/bump_crate_versions/Cargo.toml publish --dry-run
